import '../models/products.dart';

class ProductsDatabase {
  static final List<Product> initialProducts = [
    Product(
      market_name: 'Continente Bom Dia Vale Formoso',
      product_description: 'Ovos Médios 6 unidades',
      old_price: 1.90,
      new_price: 0.70,
      quantity: 1,
      expiration_date: '2023-05-17',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/ovos.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Bom Dia Vale Formoso',
      product_description: 'Salada Ibérica 200gr',
      old_price: 1.39,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-17',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/salada.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Bom Dia Vale Formoso',
      product_description: 'Sopa de Agrião 600gr',
      old_price: 2.10,
      new_price: 1.10,
      quantity: 1,
      expiration_date: '2023-05-19',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/sopa.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Bom Dia Via Catarina Shopping',
      product_description: 'Sopa de Espinafres 600gr',
      old_price: 2.10,
      new_price: 1.10,
      quantity: 1,
      expiration_date: '2023-05-18',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/sopa.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Bom Dia Via Catarina Shopping',
      product_description: 'Peito de Frango 1.2kg',
      old_price: 8.15,
      new_price: 6.40,
      quantity: 1,
      expiration_date: '2023-05-16',
      to_buy: 'não',
      category: 'Peixe e Talho',
      product_image: 'assets/images/frango.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Bom Dia Via Catarina Shopping',
      product_description: 'Nuggets de Soja 400gr',
      old_price: 4.99,
      new_price: 2.29,
      quantity: 1,
      expiration_date: '2023-05-18',
      to_buy: 'não',
      category: 'Refeições Fáceis',
      product_image: 'assets/images/nuggets.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Bom Dia Via Catarina Shopping',
      product_description: 'Salada Ibérica 200gr',
      old_price: 1.39,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-16',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/salada.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
        market_name: 'Continente Bom Dia Via Catarina Shopping',
        product_description: 'Bacalhau à brás 300gr',
        old_price: 2.49,
        new_price: 1.10,
        quantity: 1,
        expiration_date: '2023-05-18',
        to_buy: 'não',
        category: 'Refeições Fáceis',
        product_image: 'assets/images/bacalhaubras.png',
        store_image: 'assets/images/continente.png'),
    Product(
        market_name: 'Continente Bom Dia Asprela',
        product_description: 'Sopa de Espinafres 600gr',
        old_price: 2.10,
        new_price: 1.10,
        quantity: 1,
        expiration_date: '2023-05-20',
        to_buy: 'não',
        category: 'Frutas e Legumes',
        product_image: 'assets/images/sopa.png',
        store_image: 'assets/images/continente.png'),
    Product(
        market_name: 'Continente Bom Dia Asprela',
        product_description: 'Ovos Médios 6 unidades',
        old_price: 1.90,
        new_price: 0.70,
        quantity: 1,
        expiration_date: '2023-05-20',
        to_buy: 'não',
        category: 'Laticínios e Ovos',
        product_image: 'assets/images/ovos.png',
        store_image: 'assets/images/continente.png'),
    Product(
        market_name: 'Continente Bom Dia Asprela',
        product_description: 'Arroz de Pato 250gr',
        old_price: 2.99,
        new_price: 1.99,
        quantity: 1,
        expiration_date: '2023-05-20',
        to_buy: 'não',
        category: 'Refeições Fáceis',
        product_image: 'assets/images/arrozpato.png',
        store_image: 'assets/images/continente.png'),
    Product(
        market_name: 'Continente Bom Dia Asprela',
        product_description: 'Ovos Médios 6 unidades',
        old_price: 1.90,
        new_price: 0.70,
        quantity: 1,
        expiration_date: '2023-05-17',
        to_buy: 'não',
        category: 'Laticínios e Ovos',
        product_image: 'assets/images/ovos.png',
        store_image: 'assets/images/continente.png'),
    Product(
        market_name: 'Continente Bom Dia Asprela',
        product_description: 'Iogurtes s/ lactose banana 4 unidades',
        old_price: 2.19,
        new_price: 1.39,
        quantity: 1,
        expiration_date: '2023-05-20',
        to_buy: 'não',
        category: 'Laticínios e Ovos',
        product_image: 'assets/images/iogurtes.png',
        store_image: 'assets/images/continente.png'),
    Product(
      market_name: 'Continente Modelo Gaia (Rechousa)',
      product_description: 'Sopa de Agrião 600gr',
      old_price: 2.10,
      new_price: 1.10,
      quantity: 1,
      expiration_date: '2023-05-18',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/sopa.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Modelo Gaia (Rechousa)',
      product_description: 'Pão de forma 650gr',
      old_price: 1.39,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-19',
      to_buy: 'não',
      category: 'Padaria e Pastelaria',
      product_image: 'assets/images/pao.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Modelo Gaia (Rechousa)',
      product_description: 'Ovos Grandes 6 unidades',
      old_price: 2.10,
      new_price: 0.89,
      quantity: 1,
      expiration_date: '2023-05-20',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/ovos.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Modelo Gaia (Rechousa)',
      product_description: 'Queijo limiano 200gr',
      old_price: 2.39,
      new_price: 1.99,
      quantity: 1,
      expiration_date: '2023-05-20',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/queijo.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Continente Modelo Gaia (Rechousa)',
      product_description: 'Peito de Frango 1.2kg',
      old_price: 8.15,
      new_price: 6.40,
      quantity: 1,
      expiration_date: '2023-05-20',
      to_buy: 'não',
      category: 'Peixe e Talho',
      product_image: 'assets/images/frango.png',
      store_image: 'assets/images/continente.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Nuggets de Soja 350gr',
      old_price: 4.59,
      new_price: 2.19,
      quantity: 1,
      expiration_date: '2023-05-16',
      to_buy: 'não',
      category: 'Refeições Fáceis',
      product_image: 'assets/images/nuggets.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Salada Ibérica 200gr',
      old_price: 1.39,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-21',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/salada.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Leite Fresco Magro 1L',
      old_price: 0.99,
      new_price: 0.59,
      quantity: 1,
      expiration_date: '2023-05-21',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/leite.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Queijo limiano 200gr',
      old_price: 2.39,
      new_price: 1.99,
      quantity: 1,
      expiration_date: '2023-05-18',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/queijo.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Sopa de Espinafres 600gr',
      old_price: 2.10,
      new_price: 1.10,
      quantity: 1,
      expiration_date: '2023-05-21',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/sopa.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Salada Ibérica 200gr',
      old_price: 1.39,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-20',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/salada.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Leite Fresco Gordo 1L',
      old_price: 0.99,
      new_price: 0.59,
      quantity: 1,
      expiration_date: '2023-05-18',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/leite.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Brio Supermercado Biológico Picoas',
      product_description: 'Iogurtes côco 4 unidades',
      old_price: 1.89,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-17',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/iogurtes.png',
      store_image: 'assets/images/brio.png',
    ),
    Product(
      market_name: 'Apolónia Almancil',
      product_description: 'Queijo limiano 200gr',
      old_price: 2.39,
      new_price: 1.99,
      quantity: 1,
      expiration_date: '2023-05-19',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/queijo.png',
      store_image: 'assets/images/apolonia.jpg',
    ),
    Product(
      market_name: 'Apolónia Almancil',
      product_description: 'Leite Fresco Magro 1L',
      old_price: 0.99,
      new_price: 0.59,
      quantity: 1,
      expiration_date: '2023-05-19',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/leite.png',
      store_image: 'assets/images/apolonia.jpg',
    ),
    Product(
      market_name: 'Apolónia Almancil',
      product_description: 'Ovos Grandes 6 unidades',
      old_price: 2.30,
      new_price: 0.99,
      quantity: 1,
      expiration_date: '2023-05-19',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/ovos.png',
      store_image: 'assets/images/apolonia.jpg',
    ),
    Product(
      market_name: 'Apolónia Lagoa',
      product_description: 'Sopa de Agrião 600gr',
      old_price: 2.10,
      new_price: 1.10,
      quantity: 1,
      expiration_date: '2023-05-21',
      to_buy: 'não',
      category: 'Frutas e Legumes',
      product_image: 'assets/images/sopa.png',
      store_image: 'assets/images/apolonia.jpg',
    ),
    Product(
      market_name: 'Apolónia Lagoa',
      product_description: 'Gelatina Pronta Morango 400gr',
      old_price: 0.95,
      new_price: 0.55,
      quantity: 1,
      expiration_date: '2023-05-16',
      to_buy: 'não',
      category: 'Refeições Fáceis',
      product_image: 'assets/images/gelatina.png',
      store_image: 'assets/images/apolonia.jpg',
    ),
    Product(
      market_name: 'Apolónia Lagoa',
      product_description: 'Iogurtes côco 4 unidades',
      old_price: 1.89,
      new_price: 0.79,
      quantity: 1,
      expiration_date: '2023-05-21',
      to_buy: 'não',
      category: 'Laticínios e Ovos',
      product_image: 'assets/images/iogurtes.png',
      store_image: 'assets/images/apolonia.jpg',
    )
  ];
}
